### ISSUE TITLE
How to update the code to scrap multiple pages? 

### ISSUE THREAD

**Issue by youikim** [scrapehero-code/amazon-review-scraper#4]
Hi there, thank you for the code. It is really helpful. 

but I would like to ask which part of the code should be updated to scrap multiple pages. It only scraps the first page even though I put multiple pages in 'urls.txt'. Is there any easy fix solution for the issue? 

for example, when I put five different urls like below, it only read the first one and kept repeating the same result for five times. 

https://www.amazon.com/2030-Biggest-Collide-Reshape-Everything/product-reviews/1250268176/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=1
https://www.amazon.com/2030-Biggest-Collide-Reshape-Everything/product-reviews/1250268176/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2
https://www.amazon.com/2030-Biggest-Collide-Reshape-Everything/product-reviews/1250268176/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=3
https://www.amazon.com/2030-Biggest-Collide-Reshape-Everything/product-reviews/1250268176/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=4
https://www.amazon.com/2030-Biggest-Collide-Reshape-Everything/product-reviews/1250268176/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=5

Thank you.

**Comment by youikim** [comment]
solved

**Comment by jimmy10023** [comment]
Hi, I'm having the same problem, how did you solve it?
